---
title: "Suda_2002_Telomere_Modeling"
author: "Dave_Halvorsen"
date: "January 6, 2019"
output: html_document
---

```{r}
# according to Suda 2002 there should be a linear relationship between chromosome length and telomere length
# Suda 2002 Table 1 chromosome size (megabases)
chromosome_lengths <- c(246, 202, 193, 184, 173, 160, 146, 125, 110, 103, 100, 93, 85, 81, 62, 67, 48, 52)
# Suda 2002 Table 1 telomere length (bp). This is after they subtacted 2000 bp (to remove subtelomeric region)
all_telomere_lengths <- c(5681, 5681, 4987, 5018, 4589, 4302, 4127, 3922, 3708,3708,3708,3708, 4045, 3624, 3460, 3109, 3077, 3007, 2750, 2913, 2735, 2806)
telomere_lengths <- c(5681, 4987, 5018, 4589, 4302, 4127, 3922, 3708, 4045, 3624, 3460, 3109, 3077, 3007, 2750, 2913, 2735, 2806)
# these should be 18 long cause that's how many rows Suda 2002 has
length(all_telomere_lengths)
length(chromosome_lengths)
length(telomere_lengths)

plot(chromosome_lengths, telomere_lengths, main ="Telomere and Chromosome Lengths are Linearly Related", xlab="Chromosome Lengths (Mb)", ylab="Telomere Lenghts (bp)")
```

```{r}
# this is a linear regression of the variables
lm(telomere_lengths ~ chromosome_lengths)
```

```{r}
# here I'm using abline to add the line of regression
# it looks good! 
plot(chromosome_lengths, telomere_lengths, main ="Telomere Lengths are Linearly Related to Chromosome Lengths", xlab="Chromosome Lengths (Mb)", ylab="Telomere Lenghts (bp)")
abline(1920.25, 14.93)
```

```{r}
# AWESOME! The y = mx + b is y = 14.93x + 1920.25
# let's check the math here
# an x of 50 should 2750ish for y
14.93*50 + 1920.25
# an x of 250 should be 5500ish on the y
14.93*250 + 1920.25
```

```{r}
# I'm assuming that this relationship will hold true for chromosomes X + Y
# AND that p/q is 1 in telomerase (CITATION NEEDED) and that it's fine
# to think of chromsomes 1+2 having equal telomere lengths AND that same deal for 9-12
# I need to calculate lengths for chromosome x and chromosome y
# Morton 1991 Parameters of the human genome Table 1 has data I can play with
# BUT, keep in mind that the chromosome Mb are slightly different from Suda 2002
# using y=mx+b to get x length
# NOTE that the Suda 2002 cell line is from a male, so it's XY
chromosome_X_length <- 14.93*164 + 1920.25
chromosome_X_length
# using y=mx+b to get y length
chromosome_Y_length <- 14.93*59 + 1920.25
chromosome_Y_length
# adding in the missing telomere lengths
chromosome_1_length <- telomere_lengths[1]
chromosome_2_length <- telomere_lengths[1]
chromosome_9_length <- telomere_lengths[8]
chromosome_10_length <- telomere_lengths[8]
chromosome_11_length <-telomere_lengths[8]
chromosome_12_length <- telomere_lengths[8]
```

```{r}
# telomere_lengths is from Suda 2002. I wanna update it to have:
# individual lengths for C1+2
# individual lengths for C9-12
# individual lengths for X & Y 
# ^ REMEMBER that X and Y are on different pairs of chromosomes!!!
# So, the diploid chromosome would be missing C2, C10, C11, C12, and X (OR Y)
# that's 5 less than 23, so initial length should be 18
length(telomere_lengths)
telomere_lengths
```

```{r}
# here's the complete list of lengths for autosomal chromosomes 1-22 and sex chromosomes x and y
chrom_1 <- chromosome_1_length
chrom_2 <- chromosome_2_length
chrom_3 <- telomere_lengths[2]
chrom_4 <- telomere_lengths[3]
chrom_5 <- telomere_lengths[4]
chrom_6 <- telomere_lengths[5]
chrom_7 <- telomere_lengths[6]
chrom_8 <- telomere_lengths[7]
chrom_9 <- chromosome_9_length
chrom_10 <- chromosome_10_length
chrom_11 <- chromosome_11_length
chrom_12 <- chromosome_12_length
chrom_13 <- telomere_lengths[9]
chrom_14 <- telomere_lengths[10]
chrom_15 <- telomere_lengths[11]
chrom_16 <- telomere_lengths[12]
chrom_17 <- telomere_lengths[13]
chrom_18 <- telomere_lengths[14]
chrom_19 <- telomere_lengths[15]
chrom_20 <- telomere_lengths[16]
chrom_21 <- telomere_lengths[17]
chrom_22 <- telomere_lengths[18]
# suda 2002 doesn't look into chromosomes x or y ... I might play with this later
chrom_X <- chromosome_X_length
chrom_Y <- chromosome_Y_length
test <- c(chrom_1, chrom_2, chrom_3, chrom_4, chrom_5, chrom_6, chrom_7, chrom_8, chrom_9, chrom_10, chrom_11, chrom_12,chrom_13,chrom_14,chrom_15,chrom_16,chrom_17,chrom_18,chrom_19,chrom_20, chrom_21, chrom_22, chrom_X, chrom_Y)
mean(test)
mean(test)-2000
min(test-2000)/48
mean(test-2000)/48
```

```{r}
# this set has the X chromosome
#chromosome_pair_1_telomere_lengths <- c(chrom_1, chrom_2, chrom_3, chrom_4, chrom_5, chrom_6, chrom_7, chrom_8, chrom_9, chrom_10, chrom_11, chrom_12,chrom_13,chrom_14,chrom_15,chrom_16,chrom_17,chrom_18,chrom_19,chrom_20, chrom_21, chrom_22, chrom_X)
# this set has the Y chromosome
#chromosome_pair_2_telomere_lengths <- c(chrom_1, chrom_2, chrom_3, chrom_4, chrom_5, chrom_6, chrom_7, chrom_8, chrom_9, chrom_10, chrom_11, chrom_12,chrom_13,chrom_14,chrom_15,chrom_16,chrom_17,chrom_18,chrom_19,chrom_20, chrom_21, chrom_22, chrom_Y)
# this is just chromosomes 1-22 (it's what I'll be using)
#telomerase_chromosome_lengths <- c(chrom_1, chrom_2, chrom_3, chrom_4, chrom_5, chrom_6, chrom_7, chrom_8, chrom_9, chrom_10, chrom_11, chrom_12,chrom_13,chrom_14,chrom_15,chrom_16,chrom_17,chrom_18,chrom_19,chrom_20, chrom_21, chrom_22)
# removing 2, 10, 11, 12
#telomerase_chromosome_lengths <- c(chrom_1, chrom_3, chrom_4, chrom_5, chrom_6, chrom_7, chrom_8, chrom_9,chrom_13,chrom_14,chrom_15,chrom_16,chrom_17,chrom_18,chrom_19,chrom_20, chrom_21, chrom_22)
telomerase_chromosome_lengths <- c(chrom_1, chrom_2, chrom_3, chrom_4, chrom_5, chrom_6, chrom_7, chrom_8, chrom_9, chrom_10, chrom_11, chrom_12,chrom_13,chrom_14,chrom_15,chrom_16,chrom_17,chrom_18,chrom_19,chrom_20, chrom_21, chrom_22, chrom_X, chrom_Y)
```

```{r}
# here are the labels for chromosome pair set 1 and set 2
#chromosome_pair_1_names <- c((1:22), "X")
#chromosome_pair_2_names <- c((1:22), "Y")
#telomerase_chromosome_names <- c(1:22)
# c(1:9) + c(13:22)
#one <- c(1)
#telomerase_chromosome_names <- c(1)
#three_through_nine <- c(3:9)
#thirteen_through_twenty_two <- c(13:22)
#telomerase_chromosome_names <- append(telomerase_chromosome_names, three_through_nine)
#telomerase_chromosome_names <- append(telomerase_chromosome_names, thirteen_through_twenty_two)
#telomerase_chromosome_names
#length(telomerase_chromosome_names)
telomerase_chromosome_names <- c((1:22), "X", "Y")
```

```{r}
barplot(telomerase_chromosome_lengths, names.arg=telomerase_chromosome_names, las=2, main ="GM130B Telomere Lengths", xlab="Chromosome", ylab="Telomere Lenghts (bp)", ylim=c(0,6000))
```


```{r}
# This models telomere shortening for Suda 2002
# assuming cell will stop dividing after the shortest telomere reaches 0 (or more -)
above_zero <- TRUE
division_number <- 0
# assuming subtelomere is 2000 bp
telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths - 2000
while(above_zero) {
  #print(telomerase_chromosome_lengths_play)
  #print(division_number)
  barplot(telomerase_chromosome_lengths_play, names.arg=telomerase_chromosome_names, las=2, main = paste("GM130B Senescence After ", division_number, " Divisions"), xlab="Chromosome", ylab="Telomere Lenghts (bp)", ylim=c(0,3000))
  telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_play - 48
  division_number <- division_number + 1
  if(sum((telomerase_chromosome_lengths_play) < 0) > 0) {
    above_zero <- FALSE
  }
}
```

```{r}
# This models telomere shortening for Suda 2002
# assuming cell will stop dividing after the AVERAGE telomere reaches 0 (or more -)
above_zero <- TRUE
division_number <- 0
# assuming subtelomere is 2000 bp
telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths - 2000
while(above_zero) {
  #print(telomerase_chromosome_lengths_play)
  #print(division_number)
  barplot(telomerase_chromosome_lengths_play, names.arg=telomerase_chromosome_names, las=2, main = paste("GM130B Senescence After ", division_number, " Divisions"), xlab="Chromosome", ylab="Telomere Lenghts (bp)")
  telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_play - 48
  division_number <- division_number + 1
  if(sum(mean(telomerase_chromosome_lengths_play) < 0) > 0) {
    above_zero <- FALSE
  }
}
```


```{r}
telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths
#telomerase_chromosome_lengths_play
#mean(telomerase_chromosome_lengths)
#10000/max(telomerase_chromosome_lengths)
max(telomerase_chromosome_lengths_play) - min(telomerase_chromosome_lengths_play)
#sd(telomerase_chromosome_lengths_play)
telomerase_chromosome_lengths_START <- telomerase_chromosome_lengths * 10000/max(telomerase_chromosome_lengths)
#telomerase_chromosome_lengths_START
max(telomerase_chromosome_lengths_START) - min(telomerase_chromosome_lengths_START)

telomerase_chromosome_lengths_START <- telomerase_chromosome_lengths + 10000 - max(telomerase_chromosome_lengths)
max(telomerase_chromosome_lengths_START) - min(telomerase_chromosome_lengths_START)
```

```{r}
# How long till senescence if starting max is 10K AND maintaining telomere lengths of GM130B?
above_five_thousand <- TRUE
division_number <- 0
telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_START
while(above_five_thousand) {
  
  #print(telomerase_chromosome_lengths_play)
  #print(division_number)
  barplot(telomerase_chromosome_lengths_play, names.arg=telomerase_chromosome_names, las=2, main = paste("hCell Telomere Shortening After ", division_number, " Divisions"), xlab="Chromosome", ylab="Telomere Lenghts (bp)", ylim=c(0,10000))
  abline(h=5000, col="red", lwd=3)
  abline(h=3000, col="black", lwd=3)
  division_number <- division_number + 1
  telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_play - 48
  if(sum(telomerase_chromosome_lengths_play < 5000) > 0) {
    above_five_thousand <- FALSE
  }
}
```


```{r}
# testing out the telomerase idea
# this needs to evenly add telomerase to each telomere
telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_START
practice_short <- telomerase_chromosome_lengths_START - 5000
loop_lengths <- telomerase_chromosome_lengths_START - 5000
i <- 1
j <- 1
# 50 * 24 (1-22,x, y) = 1200
telomerase_bp_capability <- 1200
while(telomerase_bp_capability > 0){
  while(j < length(practice_short)){
    goal_length <- telomerase_chromosome_lengths_play[j]
    if(practice_short[j] < goal_length){
      loop_lengths[j] <- practice_short[j] + 50
    }
    j <- j + 1
  }
  #print(telomerase_bp_capability)
  #print(i)
  i <- i + 1
  telomerase_bp_capability <- telomerase_bp_capability - 50
}
telomerase_chromosome_lengths_START
practice_short
loop_lengths
```


```{r}
# How long till senescence if starting max is 10K AND maintaining telomere lengths of GM130B?
# AND telomerase is periodically turned on? AND senescence checkpoints work.
# Telomerase extends the shortest telomeres first (Harley 2008, Cristofari 2006)
# I'm not worried about that when telomere shortening overpowers telomere lengthening
above_five_thousand <- TRUE
division_number <- 0
telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_START
while(above_five_thousand) {
  #print(telomerase_chromosome_lengths_play)
  #print(division_number)
  barplot(telomerase_chromosome_lengths_play, names.arg=telomerase_chromosome_names, las=2, main = paste("Trasient Telomerase Telomere Shortening After ", division_number, " Divisions"), xlab="Chromosome", ylab="Telomere Lenghts (bp)", ylim=c(0,10000))
  abline(h=5000, col="red", lwd=3)
  abline(h=3000, col="black", lwd=3)
  division_number <- division_number + 1
  telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_play - 48
  if(division_number %% 2){
    telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_play + 48
  }
  if(sum(telomerase_chromosome_lengths_play < 5000) > 0) {
    above_five_thousand <- FALSE
  }
  # this indicates immortality and I don't want a runaway while loop
  if(division_number > 100) {
    break
  }
}
```

```{r}
# what about a cancer with telomerase always turned on?
# telomerase + cells still have the trimming mechanism turned on
# Pickett 2009  HT1090 +TEL stuck at 7.5 kb, HeLa stuck at 4.5 kb
# overexpression of hTER HeLa 8 kb, HT1080 hTR increasingly heteogenous 9.4 kb
# I could make a complicated function to make sure things stay matched, but you get the idea ...
# I'll just make shortening equal to lengthening
above_five_thousand <- TRUE
division_number <- 0
telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_START
while(above_five_thousand) {
  #print(telomerase_chromosome_lengths_play)
  #print(division_number)
  barplot(telomerase_chromosome_lengths_play, names.arg=telomerase_chromosome_names, las=2, main = paste("Immortalized Telomerase Telomere Shortening After ", division_number, " Divisions"), xlab="Chromosome", ylab="Telomere Lenghts (bp)", ylim=c(0,10000))
  abline(h=5000, col="red", lwd=3)
  abline(h=3000, col="black", lwd=3)
  division_number <- division_number + 1
  telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_play - 48
  telomerase_chromosome_lengths_play <- telomerase_chromosome_lengths_play + 48
  if(sum(telomerase_chromosome_lengths_play < 5000) > 0) {
    above_five_thousand <- FALSE
  }
  # this indicates immortality and I don't want a runaway while loop
  if(division_number > 300) {
    break
  }
}
```

```{r}
B <- c(5, 3, 1, 8, 9, 4, 6)
cols <- rainbow(length(B))
percentlabels<- round(100*B/sum(B), 1)
pielabels<- paste(percentlabels, "%", sep="")
pie(B, main="My Best Piechart", col=cols, labels=pielabels, cex=0.8)
legend("topright", c("Mon","Tue","Wed","Thu","Fri","Sat","Sun"), cex=0.8, fill=cols)
```


```{r}
# Conomos 2012 Figure S1 C HeLa
# Pie Chart with Percentages
slices <- c(889, 74, 0, 8, (94 + 8 + 6 + 7 + 4 + 2 + 471)) 
# lbls <- c("TTAGGG", "TCAGGG", "TTCGGG", "CTAGGG", "TGAGGG", "TTGGGG", "TAAGGG", "ATAGGG", "CTAGGG", "TTTGGG", "Other")
lbls <- c("TTAGGG", "TCAGGG", "TTCGGG", "CTAGGG", "Other")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="Pie Chart of Countries")
```

```{r}
# Conomos 2012 Figure S1 C
# Pie Chart with Percentages
slices <- c(889, 74, (0 + 8 + 94 + 8 + 6 + 7 + 4 + 2 + 471)) 
lbls <- c("TTAGGG", "TCAGGG", "Other")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="HeLa Average Number of Telomeric Repeats")
```


```{r}
# Conomos 2012 Figure S1 C
# Pie Chart with Percentages
slices <- c(10165, 4466, (528 + 332 + 241 + 108 + 76 + 73 + 63 + 31 + 3231)) 
lbls <- c("TTAGGG", "TCAGGG", "Other")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="WI38-VA13/2RA Average Number of Telomeric Repeats")
```


```{r}
# ALT chromosomes have different sizes for the p and q arms, so now I'll need to take those into account. 
# the length of one set of chromosomes should be 23
one_set_of_chromosomes <- c((1:22), "X")
length(one_set_of_chromosomes)
# list of autosome pairs and sex chromosomes should be 46 long
autosome_pairs_sex_chromosomes <- c("c1a1", "c2a1", "c3a1", "c4a1", "c5a1", "c6a1", "c7a1", "c8a1", "c9a1", "c10a1", "c11a1", "c12a1", "c13a1", "c14a1", "c15a1", "c16a1", "c17a1", "c18a1", "c19a1", "c20a1", "c21a1", "c22a1", "cX", "c1a2", "c2a2", "c3a2", "c4a2", "c5a2", "c6a2", "c7a2", "c8a2", "c9a2", "c102", "c11a2", "c12a2", "c13a2", "c142", "c15a2", "c16a2", "c172", "c18a2", "c19a2", "c20a2", "c21a2", "c22a2", "cY")
length(autosome_pairs_sex_chromosomes)
# list of autosome pairs and sex chromosomes AND both arms should be 92 long
#autosome_pairs_sex_chromosomes_and_arms <- c("c1a1p", "c2a1p", "c3a1p", "c4a1p", "c5a1p", "c6a1p", "c7a1p", "c8a1p", "c9a1p", "c10a1p", "c11a1p", "c12a1p", "c13a1p", "c14a1p", "c15a1p", "c16a1p", "c17a1p", "c18a1p", "c19a1p", "c20a1p", "c21a1p", "c22a1p", "cXp", "c1a2p", "c2a2p", "c3a2p", "c4a2p", "c5a2p", "c6a2p", "c7a2p", "c8a2p", "c9a2p", "c102p", "c11a2p", "c12a2p", "c13a2p", "c142p", "c15a2p", "c16a2p", "c172p", "c18a2p", "c19a2p", "c20a2p", "c21a2p", "c22a2p", "cYp", "c1a1q", "c2a1q", "c3a1q", "c4a1q", "c5a1q", "c6a1q", "c7a1q", "c8a1q", "c9a1q", "c10a1q", "c11a1q", "c12a1q", "c13a1q", "c14a1q", "c15a1q", "c16a1q", "c17a1q", "c18a1q", "c19a1q", "c20a1q", "c21a1q", "c22a1q", "cXq", "c1a2q", "c2a2q", "c3a2q", "c4a2q", "c5a2q", "c6a2q", "c7a2q", "c8a2q", "c9a2q", "c102q", "c11a2q", "c12a2q", "c13a2q", "c142q", "c15a2q", "c16a2q", "c172q", "c18a2q", "c19a2q", "c20a2q", "c21a2q", "c22a2q", "cYq")

# I want the order of chrom1a1p, chrom1a1q, chrom1a2p ... chromXp, chromXq, chrom1a2p, chrom1a2q ... chromYp, chromYp
# this list should be 92 long
autosome_pairs_sex_chromosomes_and_arms <- c("c1a1p", "c1a1q","c2a1p","c2a1q","c3a1p","c3a1q","c4a1p","c4a1q","c5a1p","c5a1q","c6a1p","c6a1q","c7a1p","c7a1q","c8a1p","c8a1q","c9a1p","c9a1q","c10a1p","c10a1q","c11a1p","c11a1q","c12a1p","c12a1q","c13a1p","c13a1q","c14a1p","c14a1q","c15a1p","c15a1q","c16a1p","c16a1q","c17a1p","c17a1q","c18a1p","c18a1q","c19a1p","c19a1q","c20a1p","c20a1q","c21a1p","c21a1q","c22a1p","c22a1q","cXp","cXq","c1a2p","c1a2q","c2a2p","c2a2q","c3a2p","c3a2q","c4a2p","c4a2q","c5a2p","c5a2q","c6a2p","c6a2q","c7a2q", "c8a2p","c8a2q","c7a2p","c9a2q","c9a2p","c102q","c102p","c11a2q","c11a2p","c12a2p","c12a2q", "c13a2p","c13a2q", "c142p","c142q", "c15a2p", "c15a2q","c16a2p","c16a2q","c172p","c172q","c18a2p","c18a2q","c19a2p", "c19a2q","c20a2p","c20a2q", "c21a2p","c21a2q","c22a2p","c22a2q","cYp","cYq")
length(autosome_pairs_sex_chromosomes_and_arms)
```

```{r}
# Here are some of the inspiration papers for the model:
# Bryan 1995. ALT up to 50 kb (peaks at 10 and 50 kb)
# Henson 2002 less than 3kb to over 50 kb
# Murnane 1994 ALT cells sporadic +/- in telomere lengths up to 20 kb AND gradual erosion of 50 bp/ PD
# Yeager 1999 ALT pattern took 17 generations to escape culture w/clone
# LOTS OF CITATIONS FOR THIS up to 30% of ALT telomeres have undetectable telomeres MIGHT BE UNDETECTABLY SHORT CAUSE DIFF SEQUENCES
# 28 is J.N. Jeyapalan, A. Mendez-Bermudez, N. Zaffaroni, Y.E. Dubrova, N.J. Royle
# PERREM 2001 p/q arm ratios are off in ALT (p / q is 10 - 0.1)
# Henson 2010 Assaying and investigating Alternative Lengthening of Telomeres activity in human cells and cancers
# ALT makes the ratio of p/q weird. Expected to be unchanged if ALT turned off.
# Henson 2010 Assaying and investigating Alternative Lengthening of Telomeres activity in human cells and cancer
# Losses of chromosomes 13, X, and 22, gains of 2, 3, 5, and 20, and translocation/deletion events involving several common chromosomal fragile sites (CFSs) were recurrent.

# it creates a list of 92 telomeres that randomly range from 500 bp to 50,000 bp in size. 
# the p / q ratio is randomly chosen between 10 - 0.1
# p + q arm = total telomere length for the chromosome of interest

# it creates 92 telomeres
ALT_telomere_lengths <- vector("list", 92)
# these are placeholders for values that will be used throughout the program
current_telomere_length_total <- 0
current_telomere_length_Q <- 0
current_telomere_length_P <- 0
# i keeps track of the current interation. Note that each run has two iterations of adding to the tel length list
i <- 1
generate_ALT_telomeres <- function() {
  # runs for 46 items (cause 92 total and creating p and q w/ each loop)
  for(length in 1:46){
    # determine the total telomere length between 500 and 50,000 bp
    current_telomere_length <- runif(1, min=500, max=50000)
    # determine the p/q ratio between 0.1 and 10
    P_to_Q_ratio <- runif(1, 0.1, 10)
    # get the q arm length. This is some cool math! BUT, it might not be obvious
    # there are two formulas here
    # 1) p arm + q arm = total length
    # 2) p arm / q arm = ratio => p arm = ratio * q arm
    # substituting 2 into 1: ratio * q arm + q arm = total length
    current_telomere_length_Q <- current_telomere_length/(P_to_Q_ratio+1)
    # get the p arm length
    current_telomere_length_P <- current_telomere_length - current_telomere_length_Q
    # get the sum (this number is already known. I'm using it for error checking)
    current_sum_p_q <- current_telomere_length_Q+current_telomere_length_P
    # get the p/q ratio (this number is already known. I'm using it for error checking)
    determine_P_to_Q_ratio <- current_telomere_length_P / current_telomere_length_Q
    # print out the math to check by hand
    print(paste("current total length is ", current_telomere_length, "Q is ", current_telomere_length_Q, "P is ", current_telomere_length_P, " sum is ", current_sum_p_q))
    print(paste("current P_to_Q_ratio is ", P_to_Q_ratio, "Q is ", current_telomere_length_Q, "P is ", current_telomere_length_P, " P_to_Q_ratio is ", determine_P_to_Q_ratio))
    print("")
    # store current p and q arms
    ALT_telomere_lengths[i] <- current_telomere_length_P 
    i <- i + 1
    ALT_telomere_lengths[i] <- current_telomere_length_Q
    i <- i + 1
  }
  return(ALT_telomere_lengths)
}
ALT_telomere_lengths <- generate_ALT_telomeres()
```

```{r}
# This is a disgusting mess of overhwelming data
# I should look at individual pairs of chromosomes
barplot(as.numeric(ALT_telomere_lengths), names.arg=autosome_pairs_sex_chromosomes_and_arms, las=2, main="ALT+ Telomere Lengths for Chromosomes", xlab="Chromosome", ylab="Telomere Lengths (bp)", ylim=c(0,50000))
abline(h=5000, col="red", lwd=3)
abline(h=3000, col="black", lwd=3)
```

```{r}
# This is a disgusting mess of overhwelming data
# I should look at individual pairs of chromosomes
barplot(as.numeric(ALT_telomere_lengths), las=2, main="ALT+ Telomere Lengths for Chromosomes", ylim=c(0,50000))
abline(h=5000, col="red", lwd=3)
abline(h=3000, col="black", lwd=3)
```


```{r}
barplot(as.numeric(ALT_telomere_lengths[1:46]), names.arg=autosome_pairs_sex_chromosomes_and_arms[1:46], las=2, main="ALT+ Telomere Lengths for Chromosomes", ylab="Telomere Lengths (bp)", ylim=c(0,50000))
abline(h=5000, col="red", lwd=3)
abline(h=3000, col="black", lwd=3)
```

```{r}
barplot(as.numeric(ALT_telomere_lengths[47:92]), names.arg=autosome_pairs_sex_chromosomes_and_arms[47:92], las=2, main="ALT+ Telomere Lengths for Chromosomes", ylab="Telomere Lengths (bp)", ylim=c(0,50000))
abline(h=5000, col="red", lwd=3)
abline(h=3000, col="black", lwd=3)
```

```{r}
# Here are some of the inspiration papers for the model:
# Bryan 1995. ALT up to 50 kb (peaks at 10 and 50 kb)
# Henson 2002 less than 3kb to over 50 kb
# Murnane 1994 ALT cells sporadic +/- in telomere lengths up to 20 kb AND gradual erosion of 50 bp/ PD
# Yeager 1999 ALT pattern took 17 generations to escape culture w/clone
# LOTS OF CITATIONS FOR THIS up to 30% of ALT telomeres have undetectable telomeres MIGHT BE UNDETECTABLY SHORT CAUSE DIFF SEQUENCES
# 28 is J.N. Jeyapalan, A. Mendez-Bermudez, N. Zaffaroni, Y.E. Dubrova, N.J. Royle
# PERREM 2001 p/q arm ratios are off in ALT (p / q is 10 - 0.1)
# Henson 2010 Assaying and investigating Alternative Lengthening of Telomeres activity in human cells and cancers
# ALT makes the ratio of p/q weird. Expected to be unchanged if ALT turned off.
# Henson 2010 Assaying and investigating Alternative Lengthening of Telomeres activity in human cells and cancer
# Losses of chromosomes 13, X, and 22, gains of 2, 3, 5, and 20, and translocation/deletion events involving several common chromosomal fragile sites (CFSs) were recurrent.
# Sakellariouo 2013 chromosomal gains == loses

# prevents telomeres from growing > 50 kb
# maintains p/q ration to 10 - 0.1
# sporadic +/- telomere lengths up to 20 kb and gradual erosion of 50 bp / PD
# loses a chromosome if telomere length goes below 0
# gains a chromosome 
```



















